import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Error: 404 - Working In Progress</title>
        <meta name="description" content="Generated by create next app" />
      </Head>      
      <p className="font-mono text-green-500">the website is still being worked on :/</p>
    </>
  )
}
